### ISSUE TITLE
addValueChangeListener always return fromClient = true

### ISSUE THREAD

**Issue by jcgueriaud1** [FlowingCode/TwinColGridAddon#106]
In the code the addValueChangeListener always return isFromClient = true even if the event is coming from the server.

https://github.com/FlowingCode/TwinColGridAddon/blob/master/src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java#L765

Maybe one solution is to change the signature of the updateSelection with a new parameter isFromClient

**Comment by javier-godoy** [comment]
Thanks for the PR! The fix has been released in version [2.8.0](https://vaadin.com/directory/component/twincolgrid-add-on/2.8.0)
