### ISSUE TITLE
addFilterableColumn with resize

### ISSUE THREAD

**Issue by jonasrotilli** [FlowingCode/TwinColGridAddon#115]
How to use an addFilterableColumn with resize?
The user needs to be able to increase the column, because sometimes the entire text does not fit.

Is there any way to put rezise as you have in the grids in all columns, whether with filter or not?

This addon is very good!

**Comment by javier-godoy** [comment]
Hello. You need to add the filterable column with some of the overloads that accept `String key` as the last parameter, and then retrieve each column and configure it as resizable:

```
twinColGrid.addFilterableColumn(..., key);
twinColGrid.getSelectionGrid().getColumnByKey(key).setResizable(true);
twinColGrid.getAvailableGrid().getColumnByKey(key).setResizable(true);
```

(The API can certainly be improved, I'll make a note about this case)
