### ISSUE TITLE
Support for selection based on row clicks

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/TwinColGridAddon#12]
It would be great to support multi selection by clicking on rows instead of checkboxes as an alternative way of selecting items. Selecting by using keyboard and presing space would be also desirable.

**Comment by javier-godoy** [comment]
Both are actually missing features in Grid (https://github.com/vaadin/vaadin-grid-flow/issues/196, https://github.com/vaadin/vaadin-grid-flow/issues/908 ) and both provide a good UX. 
If we are going to implement any of them in the addon, it makes sense to track its progress as separate issues.

**Comment by mlopezFC** [comment]
Good idea, I've created #13 and #14 for continuing with this. Closing this one.
