### ISSUE TITLE
Items are not rendered

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/TwinColGridAddon#125]
The following example produces empty grids:

```
@Route
public class MainView extends VerticalLayout {
  public MainView() {
    List<String> options = List.of("A", "B", "C", "D", "E", "F", "G");
    TwinColGrid<String> twin = new TwinColGrid<>(options);
    twin.addColumn(x -> x, "header");
    twin.withSizeFull();
    add(twin);
  }
}
```

![image](https://user-images.githubusercontent.com/11554739/212550749-d293b8a2-77fb-4739-9b86-1e46c03d2de5.png)

I tested versions 2.8.0 2.9.1, 2.9.2-SNAPSHOT of this addon with Vaadin 23.1.17, 23.2.10 and 23.2.17

**Comment by flang** [comment]
I wasn't able to reproduce the issue. Items were properly rendered.
BTW Vaadin 23.2.15 is latest release of 23.2.x
![image](https://user-images.githubusercontent.com/605992/214368627-e387dcef-b4a3-4766-b0a6-7a346501e701.png)

**Comment by javier-godoy** [comment]
Please find [attached](https://github.com/FlowingCode/TwinColGridAddon/files/10494175/my-todo.zip). After further analysis I found that this behavior is caused by https://github.com/vaadin/web-components/issues/4584.
![image](https://user-images.githubusercontent.com/11554739/214425222-e7fd3e01-b3ff-4467-bff8-2e5b69741e88.png)


As a workaround I set `min-height: 165px` to the TwinColGrid component in application styles, so that the grid is at least as large as the buttons (which IMHO makes a good default for the addon, since it packs two grid inside of flex containers)

**Comment by flang** [comment]
Setting height to TwinColGrid parent layout works fine. IMO it's not a TwinColGrid issue.

**Comment by rodolforfq** [comment]
I'm able to reproduce this issue on both V23 and V24, when using the 2.9.2 version of the addon. I used this snippet:
public class TwinColGridAddon extends VerticalLayout {

```java
public class TwinColGridAddon extends VerticalLayout {

    public TwinColGridAddon() {
        Set<String> selectedDays = new HashSet<>();
        List<String> availableDays = List.of("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday");

        var twinColGrid = new TwinColGrid<>(availableDays)
                .addSortableColumn(String::toString, Comparator.comparing(String::toString), "Day")
                .withAvailableGridCaption("Available Options")
                .withSelectionGridCaption("Selected Options")
                .withoutAddAllButton()
                .withSizeFull()
                .withDragAndDropSupport()
                .withSelectionGridReordering()
                .selectRowOnClick();
        twinColGrid.setCaption("Weekdays Selection");
        twinColGrid.setValue(selectedDays);

        add(twinColGrid);
        setSizeFull();
    }

}
```
Notice the last line - setSizeFull(). If I don't do this to make the underlying container apply a 100% (or any other fixed height), the 2 Grids are not visible (the horizontal layout containing both of them and the buttons on the other hand, does display just fine).
