### ISSUE TITLE
Adding Listeners: Not triggering

### ISSUE THREAD

**Issue by higgsja** [FlowingCode/TwinColGridAddon#126]
TwinColGrid version 2.8.0

I am likely missing something obvious, but traced the code into TwinColGrid.java and things seem to be doing what they need to be doing but the added listeners do not fire.

My objective is to enable Cancel/Save buttons whenever there is a change in the SelectionGrid. This may not be the right way to do it and I'm open to alternatives.

I want to add a listener on the SelectionGrid that fires whenever there is a change. Most obvious is to put a listener on its DataProvider:
`this.twinColGrid.getSelectionGrid().getDataProvider().addDataProviderListener(e -> this.doSelectionChanged();`

Or, put a listener on TwinColGrid:
`this.twinColGrid.addValueChangeListener(e -> this.doSelectionChanged();`

The listeners are definitely being added but neither fires.

I did test adding something to the AvailableGrid and that does work:
`this.twinColGrid.getAvailableGrid().addSelectionListener(e -> int i = 0;`

I'm baffled.

**Comment by higgsja** [comment]
Please close/delete. PICNIC (Problem in Chair Not In Computer).

**Comment by mlopezFC** [comment]
Hi @higgsja, thanks for the update, and it is good to know that now it works for you.
Regards!
