### ISSUE TITLE
Buttons position bug on resize

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/TwinColGridAddon#154]
The buttons position is above the grid headers after resizing the tcg layout between horizontal and vertical
![tcgbug](https://github.com/FlowingCode/TwinColGridAddon/assets/71266295/0b6c587d-d27e-4e0c-affb-6120956e6889)

**Comment by javier-godoy** [comment]
I was able to reproduce the behavior in the orientation demo (by changing the initial orientation to horizontal)
![grid-orientation](https://github.com/FlowingCode/TwinColGridAddon/assets/11554739/2cb960db-83e5-461d-8d97-794d988ec05f)
