### ISSUE TITLE
Grids superposition with buttons on resizing

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/TwinColGridAddon#155]
When tcg changes its orientation, components overlaps. e.g, two tcg overlaps its grids and buttons after changing orientation, with auto resizing set to true.
![tcgbug](https://github.com/FlowingCode/TwinColGridAddon/assets/71266295/62e66fa1-ef8e-44d0-9bd8-76a8f091ad3c)

![image](https://github.com/FlowingCode/TwinColGridAddon/assets/71266295/3139539f-075b-41fd-9779-5a3acc941da9)

**Comment by javier-godoy** [comment]
Hello. I was not able to reproduce this issue.

```
    TwinColGrid<Integer> tcg1 = new TwinColGrid<>();
    TwinColGrid<Integer> tcg2 = new TwinColGrid<>();

    tcg1.setCaption("Caption");
    tcg1.setItems(IntStream.range(1, 20).boxed().toList());
    tcg1.getAvailableGrid().addColumn(x -> x).setHeader("Header");
    tcg1.getAvailableGrid().addColumn(x -> x).setHeader("Header");
    tcg1.setAutoResize(true);
    tcg1.setWidthFull();

    tcg2.setCaption("Caption");
    tcg2.setItems(IntStream.range(1, 20).boxed().toList());
    tcg2.getAvailableGrid().addColumn(x -> x).setHeader("Header");
    tcg2.getAvailableGrid().addColumn(x -> x).setHeader("Header");
    tcg2.setAutoResize(true);
    tcg2.setWidthFull();
    SplitLayout split = new SplitLayout(new VerticalLayout(tcg1, tcg2), new Span());
    split.setSizeFull();
    add(split);
```

![image](https://github.com/FlowingCode/TwinColGridAddon/assets/11554739/b742c533-1992-4052-85a7-9d48ef01f18b)

**Comment by ngonzalezpazFC** [comment]
The problem was not a TwinColGridAddon issue, it was related to the tcg container Component and I was able to fix it.
