### ISSUE TITLE
Clear throws NPE

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/TwinColGridAddon#17]
As discussed in https://github.com/FlowingCode/TwinColGridAddon/issues/16
> clear() DOES throw an exception (as of 2.0.4-SNAPSHOT) because it's implemented as setValue(getEmptyValue()) and getEmptyValue() returns null.

```java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.flowingcode.vaadin.addons.twincolgrid.TwinColGrid.setValue(TwinColGrid.java:343)
	at com.flowingcode.vaadin.addons.twincolgrid.TwinColGrid.setValue(TwinColGrid.java:1)
	at com.vaadin.flow.component.HasValue.clear(HasValue.java:179)
```

It should be documented that `setValue` does not allow null.
https://github.com/vaadin/flow/blob/907cbbd59612ac2e31daf5c1566fb48529d75200/flow-server/src/main/java/com/vaadin/flow/component/HasValue.java#L100-L102

**Comment by ngonzalezpazFlowingCode** [comment]
The sorting function works as expected. The elements of the list are not sorted until the user clicks on the sorting arrows next to the column header (as can be seen on the attached gif). As a workaround, the list could be sorted before setting it to the TwinColGrid. Maybe an extra method to sort the grids programatically is needed. (to be implemented in #31)
