### ISSUE TITLE
Remove All Button

### ISSUE THREAD

**Issue by fante76** [FlowingCode/TwinColGridAddon#4]
I think it should have a removeAll button also.

**Comment by javier-godoy** [comment]
It has both "remove all" and "add all" buttons, but they have to be enabled separately (by default, they are not shown). For instance, the first example in the [demo UI](https://github.com/FlowingCode/TwinColGridAddon/blob/master/twincolgrid-demo/src/main/java/com/flowingcode/vaadin/twincolgriddemo/MyUI.java) does:

`new TwinColGrid<>("TwinColGrid binding demo", availableBooks).showRemoveAllButton();`
