### ISSUE TITLE
Expose more Grid configuration

### ISSUE THREAD

**Issue by WoozyG** [FlowingCode/TwinColGridAddon#6]
This component is especially helpful when selecting from a large list of items with discrete attributes.  It would be even better if the left grid was exposed in such a way that we could easily add a header row for filter controls, to allow users to filter items by relevant values.  I'd be happy with a standard text filter per column, but allowing customizing would be nice.

Since the grids are final and private, I would have to modify the source or modify the class at runtime to get at the grid to call addHeaderRow().

**Comment by mlopezFC** [comment]
Thanks for sharing the feedback! .. [version 2.0.1](https://vaadin.com/directory/component/twincolgrid-add-on/2.0.1) should be already available with your proposed change. Please tell us if you find problems by using it.

**Comment by WoozyG** [comment]
Except I failed to mention we are on Vaadin 8 LTS, and can't use the 2.0+ releases :(

I also failed to flag this so I didn't get notified, or I would have provided feedback sooner.

**Comment by javier-godoy** [comment]
Reopened.

**Comment by mlopezFC** [comment]
Released for Vaadin 8 version as well (see [here](https://vaadin.com/directory/component/twincolgrid-add-on/1.0.3))
