### ISSUE TITLE
Why is the component final?  It doesn't need to be.

### ISSUE THREAD

**Issue by WoozyG** [FlowingCode/TwinColGridAddon#7]
It would be much nicer from an OO coding perspective to be able to subclass the component rather than create some sort of configurator visitor, for cases where we want similarly configured instances in multiple views.  

From the code, I can't see any purpose for making it final.

**Comment by WoozyG** [comment]
For that matter, to customize the (now protected) grid fields, one needs to create a visitor class _in the same package as the component_, since it can't be extended, in order to use the "default" access implied by "protected" access.

**Comment by javier-godoy** [comment]
Agree. The component should not be final. (This applies to both 1.x and 2.x versions.)

**Comment by mlopezFC** [comment]
[Fixed and released for both versions](https://vaadin.com/directory/component/twincolgrid-add-on)
