### ISSUE TITLE
Add support for HasValue.clear() method

### ISSUE THREAD

**Issue by paodb** [FlowingCode/TwinColGridAddon#72]
This comes from a directory comment by Paul Corbett:

"Nice effort, however, the component does not support the HasValue.clear() method. This causes a NullPointerException when the component is incorporated in an instance of type Binder and the setBean method is called with a parameter of null to clear out the fields. This makes this component unusable in our project, very disappointing."

**Comment by javier-godoy** [comment]
`getEmptyValue()` returns `null` but `setValue` requires a non-null argument.
