### ISSUE TITLE
Move items by doubleclick or similar

### ISSUE THREAD

**Issue by paodb** [FlowingCode/TwinColGridAddon#73]
This comes from directory question by Michael Thome 

"_Is there a straightforward way to enable a doubleclick (or similar) event to immediately move an item to the other column?_"

**Comment by javier-godoy** [comment]
#68 at least will allow that feature to be implemented by user code, but that would require casting the dataproviders and refreshing both lists. We can provide the same feature out-of-the-box.

**Comment by javier-godoy** [comment]
Back to triage per https://github.com/FlowingCode/TwinColGridAddon/issues/73#issuecomment-1071079710

**Comment by mlopezFC** [comment]
I think it would be something nice to have by default.
