### ISSUE TITLE
Clear all values on the right grid and reset the left grid

### ISSUE THREAD

**Issue by hhy8246** [FlowingCode/TwinColGridAddon#75]
is there a way to clear all filters of a TwinColGrid? After moving some of the items over to the right grid, there is no method to programmatically clear all the values of the right grid and reset the left grid with the original list.

**Comment by javier-godoy** [comment]
No, there isn't*. The filter fields are added to the grid header, but they cannot be retrieved programatically.

https://github.com/FlowingCode/TwinColGridAddon/blob/162514660cf959f9ef51e4aafc14c4eb22ba372a/src/main/java/com/flowingcode/vaadin/addons/twincolgrid/TwinColGrid.java#L628-L643

* Well, now that the grids are public, the filter components can be obtained from the component of each header cell, but that isn't a good approach, and we should add some public method to that effect.

**Comment by hy8246** [comment]
Here is the PR for this issue: https://github.com/FlowingCode/TwinColGridAddon/pull/78
