### ISSUE TITLE
Move all buttons ignore applied filters

### ISSUE THREAD

**Issue by paodb** [FlowingCode/TwinColGridAddon#76]
This comes from directory:

I think the default semantics of ">>" and "<<" should be that only filtered items should be moved. My users find it surprising when >> ignores applied filters.

e.g. if I have a set {Apple, Banana, Celery} and filter by "n", not only should only Banana be visible on the left, but only Banana should be moved to the right on ">>".

**Comment by hy8246** [comment]
Here is the PR for this issue: https://github.com/FlowingCode/TwinColGridAddon/pull/77
