### ISSUE TITLE
Clear is not working

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/TwinColGridAddon#80]
The "Clear TwinColGrid" button is not working in the demo. [Taking a look to the code](https://github.com/FlowingCode/TwinColGridAddon/blob/master/src/test/java/com/flowingcode/vaadin/addons/twincolgrid/BoundDemo.java#L65), nothing special is being done, so probably the clear() method is broken.

**Comment by javier-godoy** [comment]
I'm closing this issue because the feature works as expected in the [demo](https://addonsv14.flowingcode.com/twincolgrid).
