### ISSUE TITLE
Add support for vertical orientation of grids

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/TwinColGridAddon#82]
I need to replicate a view where I can use this addon, but I need the grids to be one on top of the other, with the button icons pointing towards them, up and down. For example:
![image](https://user-images.githubusercontent.com/71266295/131353809-46451b09-3cc5-4260-b3a7-2803e5407128.png)

Also, this layout could be applied if the width of the view is not greater than X pixels, making the addon responsive. Now the grids are shown squashed:
![image](https://user-images.githubusercontent.com/71266295/131342817-21880a39-444b-48cb-8807-c19d81b6dd35.png)

**Comment by javier-godoy** [comment]
For now, we'll just implement a toggle for the orientation. Responsive behavior will be investigated in #83
