### ISSUE TITLE
Implement responsive behavior

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/TwinColGridAddon#83]
Once the feature described in #82 is implemented, the component should have a responsive behavior, by switching between horizontal and vertical layout, as needed.

**Comment by mlopezFC** [comment]
It would be great that this feature can be enabled/disabled. Regarding how to to choose the orientation, maybe it should be based on the component's actual aspect ratio. If the component is wider than taller then the horizontal orientation should be automatically selected, and if it's taller than wider then the other way around.
Another enhancement would be to supply a callback so the user can decide when to select each orientation based on the size.
