### ISSUE TITLE
Infinite Loop on set required indicator visible true

### ISSUE THREAD

**Issue by ahmedmirza994** [FlowingCode/TwinColGridAddon#86]
` at com.flowingcode.vaadin.addons.twincolgrid.TwinColGrid.setRequiredIndicatorVisible(TwinColGrid.java:614) ~[twincolgrid-2.4.0.jar:2.4.0]`

I think you are missing to call super.setRequiredIndicatorVisible(value) inside your override method setRequiredIndicatorVisible.

**Comment by javier-godoy** [comment]
Thanks for the report. There is no `super.setRequiredIndicatorVisible` because TwinColGrid is a custom component, but you are right that it should have implemented `setRequiredIndicatorVisible` (and `isRequiredIndicatorVisible`, and `isReadOnly`) in a meaningful way.

**Comment by javier-godoy** [comment]
Released in v2.5.0
