### ISSUE TITLE
Replace the concepts/namings of "right" and "left" grid 

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/TwinColGridAddon#88]
Replace the concepts/namings of "right" and "left" grid (in favor of "available" and "selections" for example) since left/right is not relevant for vertical orientation or the proposed feature of swapping left and right side (#87)

**Comment by mlopezFC** [comment]
Totally agree with this, and I cannot think right now a better naming scheme other than "available" and "selections"

**Comment by javier-godoy** [comment]
Released in v2.5.0
