### ISSUE TITLE
Allow re-ordering of the right side

### ISSUE THREAD

**Issue by higgsja** [FlowingCode/TwinColGridAddon#90]
Often, we provide a list of columns to choose from for subset data display. Having chosen the appropriate columns, the client wants to then change the order with drag and drop in the 'selected' side.

Possible?

**Comment by javier-godoy** [comment]
Yes. You can set [column reordering allowed](https://vaadin.com/api/platform/14.4.4/com/vaadin/flow/component/grid/Grid.html#setColumnReorderingAllowed-boolean-) on the selection grid:
```
twinColGrid.getSelectionGrid().setColumnReorderingAllowed(true);
```

**Comment by higgsja** [comment]
Sorry if you see this twice as I replied to the email.

To be clear, after getting the subset of elements from the left to the right side, I want to be able to drag/drop or otherwise re-order the right side, i.e., move the items up and down in the selected side.

Column reordering sounds like shifting columns around. Will it really do what I'm asking?

**Comment by javier-godoy** [comment]
> Column reordering sounds like shifting columns around. Will it really do what I'm asking?

It won't. I got it wrong.

>  I want to be able to drag/drop or otherwise re-order the right side, i.e., move the items up and down in the selected side

It would require drag-and-drop listeners that handle dragging within the same grid (as in https://cookbook.vaadin.com/grid-dnd-reorder-rows), which is currently not implemented by the component. I think we can make it an optional feature of TwinColGridAddon.
